dist: trusty
script:
- export NNMS_VERSION=$(node -e "console.log((require('./package.json') || {}).version)")
- 'if [ -z ${NNMS_VERSION+x} ]; then travis_terminate 1; else echo "nnms version:
  $NNMS_VERSION"; fi'
- npm install
- npm run build
- printenv
npm:
  token:
    secure: cm90YNOVXiv+YMQ8ysUIyrMk1P0euo5+aREFa9oLTJpuL66E+K4AAX+tjJUBNSGg53CcnedXekKsjmajt/3UbA00TSbv1EIIctHR+8+WAiDVuanImBw0xfc9HJbfHK91gHOjkB8wwSXpzJq7+0Wq0NHjTW9UPTKvVITggC0OLuTA2IDLc0Zy4SVxI8x++Mr0CUkEZdwQs3KHRClyGE5zhWGGLV2r4Y5jV+BEQqcTNrGEiNPwbJRv+zHIvunQGLs9difZNNaarTZFpUjYbo8wArFHYxV8EfgZXEJwjEaHCFhfeRhFYc0IuKme4JP92vizdb/aZJ/C1Xls69PaLqlSd6t49La6QMsfbhW0SKeMsC9cmhUfU0zZUIIIIRxjhN+sMiVRhhquMmCR8HgHUcmPmiulGDlxq8CIpm4tNMwTtv8afv88pCAS72GExbeWQxb1k20a9y7Wy+7m/ZacvTJEcRAEtGSvCfNLsh0AtpccqD3fsSE+JvXwsoUugKejyX1bonQa8/s/jnHbkQt802DBDtTZH9Lh3cOM+Ve7SAI7qxJ2fCtcPSzdjccsNp2z3jkSHMKoPsCUzgWt6BPq7ezKeYv6T3fydb8G2VxGEfhHU4UNIUPSo6282cDXuIOr1YpIk0UgEDy7qMP3ulwaJCrLMBK6Ct6JE0RDBtncvPr8jc0=
