dist: trusty
jobs:
  include:
    - stage: install
      script:
        - export NNMS_VERSION=$(node -e "console.log((require('./package.json') || {}).version)")
        - printenv
        - travis_terminate 1
        - echo FOO
