dist: trusty
jobs:
  include:
    - stage: install
      script:
      - export NNMS_VERSION=$(node -e "(require('./package.json') || {}).version")
      - cat ./package.json
      - echo "nnms:$NNMS_VERSION"
      - docker pull "nnms:$NNMS_VERSION"
